# Generated by Django 5.1.7 on 2025-03-11 18:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
