# Generated by Django 5.1.7 on 2025-03-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_transaction_check_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/jiscollege.png', null=True, upload_to='profile_pics/'),
        ),
    ]
